import React from "react";
import Mentors from "../../components/Mentors";
import Head from "next/head";
import Navbar from "../../components/Navbar";

function Apply() {
    return (
        <div className="h-screen w-screen overflow-hidden">
            <Head>
                <title>Ensight | Educational Insight</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col h-full bg-sky-100 overflow-y-scroll scrollbar-hide">
                <Navbar />
                <h1 className="font-extrabold text-4xl mx-auto font-comicsans mt-4">
                    Mentorship Form
                </h1>
                <div className="mx-auto mt-20">
                    <Mentors />
                </div>
            </main>
        </div>
    );
}

export default Apply;
