import Head from 'next/head'
import Mentorship from '../../components/Mentorship'
import Navbar from '../../components/Navbar'

export default function Home() {
  return (
    <div className="h-screen w-screen overflow-hidden">
      <Head>
        <title>Ensight | Educational Insight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col h-full bg-sky-100'>
        <Navbar/>
        <Mentorship/>
      </main>
      
    </div>
  )
}
