import Head from 'next/head'
import Navbar from '../../components/Navbar'

export default function Home() {
    
  return (

    <div className="h-screen w-screen overflow-hidden">
      <Head>
        <title>Ensight | Educational Insight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col h-full bg-sky-100'>
        <Navbar/>
        <h1 className='text-6xl text-center mt-20 font-extrabold font-comicsans'>COMING SOON</h1>
      </main>
      
    </div>
  )
}
