import { collection, doc, getDocs, query, where } from "firebase/firestore";
import React from "react";
import { db } from "../../firebase/firebase";
import Head from "next/head";
import Navbar from "../../components/Navbar";

function CourseDetails({ renderer }) {
    return (
        <div className="h-screen w-screen overflow-hidden">
            <Head>
                <title>{renderer?.title} | Ensight</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col h-full bg-sky-100">
                <Navbar />
                <div className=" w-[80%] mx-auto">
                    <h1 className="text-center text-4xl font-comicsans py-6">{renderer?.title}</h1>

                    <p className="text-lg">{renderer?.data}</p>

                    <button>Go to Course</button>
                </div>
            </main>
        </div>
    );
}

export default CourseDetails;

export async function getServerSideProps(context) {
    const link = context.query.link;
    const ref = query(collection(db, "courses"), where("link", "==", link));

    const data = await getDocs(ref);

    const renderer = data?.docs?.[0].data();

    console.log(data);
    return {
        props: {
            renderer,
        },
    };
}
