import Head from "next/head";
import Courses from "../../components/Courses";
import Navbar from "../../components/Navbar";

export default function Programs() {
    return (
        <div className="h-screen w-screen overflow-hidden">
            <Head>
                <title>Programs | Ensight</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col h-full bg-sky-100">
                <Navbar />
                <Courses />
            </main>
        </div>
    );
}
