import React from "react";
import Head from "next/head";
import Navbar from "../../components/Navbar";

function Faqs() {
    const data = [
        {
            question: "Why should I opt for ensight?",
            answer: "Ensight provides you the professional curated content by Indian instructors along with live doubt solving and personal one to one mentorship which you won't find anywhere else. The courses are prepared by students under the guidance of experts which increases the relatability for the students who are viewing the course.",
        },
        {
            question:
                "Why don’t we provide live classes, what are the benefits of recorded lectures?",
            answer: "The concept of live classes is old-fashioned, recorded lectures + live doubt/mentorship is an easy way to educate lakhs of students at the same time. The time of exports/ mentors is also saved, so they can focus on more such courses to give the best kind of knowledge to the students across the country.",
        },
        {
            question: "Will personal mentors be allotted to individuals?",
            answer: "The allotment of mentors  depends on their availability, It also depends on the fact for what purpose you seek mentorship, is it a general doubt or specific doubt.",
        },
    ];
    return (
        <div className="h-screen w-screen overflow-hidden">
            <Head>
                <title>Ensight | Educational Insight</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col h-full bg-sky-100">
                <Navbar />
                <div className="w-[80%] mx-auto my-10">
                    <h1 className="text-4xl my-4 font-comicsans">Frequenty Asked Questions</h1>
                    <div className="space-y-6">
                        {data.map((q, i) => (
                            <Faquestion
                                key={i}
                                question={q.question}
                                answer={q.answer}
                            />
                        ))}
                    </div>
                </div>
            </main>
        </div>
    );
}

export default Faqs;

const Faquestion = ({ question, answer }) => {
    return (
        <div className="border-b border-gray-300 space-y-2 pb-4">
            <p>
                <span className="font-bold text-sm">Question: </span>
                {question}
            </p>
            <p>
                <span className="font-bold text-sm">Answer: </span>
                {answer}
            </p>
        </div>
    );
};
